### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by mrgrauel** [Manoz/Cookies-F-cker#1]
Hey,

is it possible to build this extension for Safari on macOS? I haven't looked up the api, but it would be awesome. Maybe you know something about it. If not would it be ok if I use your code base for an extension?

Regards,
Andreas

**Comment by Manoz** [comment]
Hey, I have no idea how to build this on macOS but it's a good idea. 

I will update this extension soon (for Chrome) and wanted to add Firefox support. 

Feel free to use my code. Keep in mind that this was my very first Chrome extension so the code is probably a bit ugly 😁

It would be nice if you could make a PR so I can add the Safari version to the releases and add you as collaborator on this repo of course. It’s up to you :)

**Comment by Manoz** [comment]
Hey @mrgrauel 

Looks like I can't create the Safari version. I updated my extension today so feel free to grab everything and build your own extension for Safari.
**Cookies-F-cker** is very simple. As you can see in the source code it just hides the cookies policy popups but does not accept them for you. Should be easy to do a Safari version tho :)
